services:
  database:
    image: postgres:16.4
    hostname: feedback-portal-db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  app:
    image: ozoneteam/feedback-portal:latest
    hostname: feedback-portal-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/test
      APP_URL: http://localhost:3000

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5433/portal
    depends_on:
      - database


volumes:
  data: