services:
  database:
    container_name: loop-in-db
    image: postgres:latest
    environment:
      POSTGRES_DB: loop-in
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: mysupersecretpassword
    healthcheck:
      test: [ "CMD-SHELL", "sh -c", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - data:/var/lib/postgresql/data

  app:
    container_name: loop-in-app
    image: ozoneteam/loop-in:latest
    ports:
      - "3000:3000"
    volumes:
      - public:/app/public
    depends_on:
      - database
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres_user:mysupersecretpassword@database:5432/loop-in

volumes:
  data:
  public: