
services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_DB: portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: