services:
  database:
    container_name: loop-in-db
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
      POSTGRES_DB: loop-in
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: mysupersecretpassword
    healthcheck:
      test: [ "CMD-SHELL", "sh -c", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  public: