import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import {GetConfig} from "@/lib/config";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Feedback Portal",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode
}

export default async function RootLayout({children}: Readonly<RootLayoutProps>) {

    const config = await GetConfig('site_logo')

    return (
        <html lang="en">
        <head>
            <link rel={'icon'} href={config.site_logo || '/logo.svg'} type={'image/x-icon'} sizes={'any'}/>
        </head>
        <body className={inter.className + ' mobile:overflow-x-hidden'}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
